apiVersion: v1
kind: Service
metadata:
  name: moments
spec:
  selector:
    app: moments
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
   name: moments-config
data:
 uri: mongodb+srv://admin:root@cluster0.vwpz2pv.mongodb.net/moments_db?retryWrites=true&w=majority
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moments
  template:
    metadata:
      labels:
        app: moments
    spec:
      containers:
        - name: moments
          image: gcr.io/daisyduck-reborn/moments:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: moments-config  
                  key: uri