apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: moments
build:
  artifacts:
    - image: moments
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml
