apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: moments
build:
  artifacts:
    - image: gcr.io/daisyduck-reborn/moments
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - config/dev/application.deployment.yaml